In [368]:
import numpy as np
import matplotlib.pyplot as plt
from importlib import reload
import tgs, rgs
reload(tgs) 
reload(rgs) 


<module 'rgs' from '/Users/gordonwongyl/Documents/ORF/Reproduce_result/rgs.py'>

In [369]:
GAMMA = np.array([2e9, 100e9, 170e6, 100e9]) * 2 * np.pi
T_SPIN_COHERENCE = [13e-3, 4e-6, 1., 1.]
L_neighbour = [1.7e3, 30.3e3, 1.8e3, 1.7e3]
BRANCH_PARAM = [np.array([4,16,5]), np.array([1,1,19]), np.array([4,18,5]), np.array([4,16,5])]
L_delay = [398, 80.4, 627.9, 380.7]

L = 1000e3
L_ATT = 20e3

for i in range(len(GAMMA)):
    M = L/L_neighbour[i] - 1
    miu = tgs.Miu(L, L_ATT, L_delay=L_delay[i], m=M)
    tree = tgs.Tree_ancilla(BRANCH_PARAM[i], miu=miu)
    time = tgs.Time(GAMMA[i], 500)
    error = tgs.Error(tree, time, t_spin_coherence=T_SPIN_COHERENCE[i])

    print(tree.R)
    print("M:", M)
    # print("Miu: ", tree.miu_total(delay_apply=False))
    # print("Tree P_succ", tree.P_succ)
    # print("Tree_ T graph:", tree.T_tree(time))
    # print("e_incorrect:", error.e_incorrect)
    print("R_eff: ", tgs.effective_key_rate(tree, time, error, M, 2))
    print()


e_sp:  3.420942321458739e-05
miu 0.12741332981861553
[0.99973596 0.99991018 0.99996642]
M: 587.2352941176471
fidelity: 0.9722680186970342753
key_rate: 0.68449731159289993845
R_eff:  2640.0859973303215202

e_sp:  0.0015719372448598989
miu 0.7911822243946263
[2.06888928e-01 2.48689958e-14 9.88325080e-01]
M: 32.00330033003301
fidelity: 0.9494048777766361802
key_rate: 0.49217413192385653446
R_eff:  3.8797236227187776568e-17

e_sp:  3.336714097594485e-05
miu 0.13176537399233323
[0.99969781 0.99995754 0.99996028]
M: 554.5555555555555
fidelity: 0.9744970395356445936
key_rate: 0.70513733444350818635
R_eff:  854.76710112484905213

e_sp:  3.334240881558699e-05
miu 0.12741332981861553
[0.99973596 0.99991018 0.99996642]
M: 587.2352941176471
fidelity: 0.97296210459973020424
key_rate: 0.6908794297709688255
R_eff:  3344.0385096199860184



In [346]:
GAMMA = np.array([2e9, 100e9, 170e6, 100e9]) * 2 * np.pi
T_SPIN_COHERENCE = [13e-3, 4e-6, 1., 1.]
L_neighbour = [1.1e3, 2.2e3, 27e3, 1.9e3]
BRANCH_PARAM = [np.array([4,16,5]), np.array([4,22,6]), np.array([1,1,18]), np.array([4,15,5])]
L_feedback = [540.3, 16.5, 93.6, 11.3]
L_delay = [1.2e3, 37.1, 378., 25.6]

L = 1000e3
L_ATT = 20e3

for i in range(4):
    M = L/L_neighbour[i] - 1
    miu = tgs.Miu(L, L_ATT, L_delay=L_delay[i], m=M, L_feedback=L_feedback[i])
    tree = tgs.Tree_feedback(BRANCH_PARAM[i], miu=miu)
    time = tgs.Time(GAMMA[i], 500)
    error = tgs.Error(tree, time, t_spin_coherence=T_SPIN_COHERENCE[i])

    # print("M:", M)
    # print("Miu: ", tree.miu_total(delay_apply=False))
    # print("Tree P_succ", tree.P_succ)
    # print("Tree_ T graph:", tree.T_tree(time))
    # print("e_incorrect: ", error.e_incorrect)
    print("R_eff: ", tgs.effective_key_rate(tree, time, error, M, 1))
    print()



0.10083910944419039
e_sp:  3.3900434006888815e-05
miu 0.10083910944419039
fidelity: 0.9651645683113831975
key_rate: 0.62128857884707053294
R_eff:  5348.3814366165690304

0.14895757146829824
e_sp:  6.805523544877136e-05
miu 0.14895757146829824
fidelity: 0.95846831502337392905
key_rate: 0.5647622317069177164
R_eff:  270432.33447677267515

0.7537217523864032
e_sp:  3.339344621806011e-05
miu 0.7537217523864032
fidelity: 0.9987639495851396987
key_rate: 0.9775630828166163847
R_eff:  1.36974726696793735885e-17

0.13609571225518025
e_sp:  3.333349928456864e-05
miu 0.13609571225518025
fidelity: 0.97145028243292508296
key_rate: 0.6770284924812837652
R_eff:  386891.79985093300604



In [367]:
GAMMA = np.array([2e9, 100e9, 170e6, 100e9]) * 2 * np.pi
T_SPIN_COHERENCE = [13e-3, 4e-6, 1., 1.]
L_neighbour = [3.2e3, 500e3, 3.1e3, 3.2e3]
N = [32, 4, 32, 32]
BRANCH_PARAM = [np.array([24,7]), np.array([1,1]), np.array([24,7]), np.array([24,7])]
L_delay = [483.5, 20., 516.6, 480.5]

L = 1000e3
L_ATT = 20e3

for i in range(4):
    M = round(L/L_neighbour[i] - 1)
    miu = tgs.Miu(L/2, L_ATT, L_delay=L_delay[i], m=M)
    rgs_ancilla = rgs.RGS_ancilla(BRANCH_PARAM[i], N[i], miu=miu)
    time = tgs.Time(GAMMA[i], 500)
    error = rgs.RGS_Error(rgs_ancilla, time, T_SPIN_COHERENCE[i])
    # R_eff = rgs.effective_key_rate(rgs_ancilla, time, error, M, 3, L, L_ATT)

    print("M:", M)
    # print("Miu: ", rgs_ancilla.miu_total)
    # print("RGS P_succ", rgs_ancilla.P_succ)
    # print("RGS T graph:", rgs_ancilla.T_graph(time))
    print("R_eff: ", rgs.effective_key_rate(rgs_ancilla, time, error, M, 3, L, L_ATT))
    print()
    

0.12292739213815662
e_sp:  3.3859099809436434e-05
miu 0.12292739213815662
M: 312
fidelity: 0.9648990753790010063
key_rate: 0.6189946850506284028
R_eff:  332.30858820905231252

0.9999964596794866
e_sp:  0.012383913684356887
miu 0.9999964596794866
M: 1
fidelity: 0.8636566207291334979
key_rate: -0.05501555220038094538
R_eff:  -7.4427089430450249104e-81

0.12075586243650638
e_sp:  3.334117424490623e-05
miu 0.12075586243650638
M: 322
fidelity: 0.96472250514670550016
key_rate: 0.6174716369592717945
R_eff:  282.16252584492061842

0.12292739213815662
e_sp:  3.334007672167667e-05
miu 0.12292739213815662
M: 312
fidelity: 0.96542505965338833596
key_rate: 0.62354374851719890274
R_eff:  339.2968840142396355



In [361]:
# Check with data in A3
miu_set = [np.float128(0.2), 0.27]
e_m_set = [2.8e-5, 5.6e-5]
BRANCH_PARAM = [[np.array([16,14,1], dtype=int), np.array([11, 11, 1])], 
                [np.array([17,28,2]), np.array([12,23,2])]]

for i in range(2):
    for j in range(2):
        miu = tgs.Miu(1000, 100, 0, 0, 0, miu_set=miu_set[i])
        time = tgs.Time(2e9, 500) # shouldn't matter
        rgs_test = rgs.RGS_ancilla(BRANCH_PARAM[i][j], 0, miu=miu)

        error = rgs.RGS_Error(rgs_test, time, 0, epsilon_sp_measure_set=e_m_set[i])
        print("1 - PZ: ", np.float128(1.0) - rgs_test.prob_Z_measurement)
        print("1 - PX: ", np.float128(1.0) - rgs_test.prob_X_measurement)

        print("ez: ", error.epsilon_Z)
        print("ex: ", error.epsilon_X)

        print("1 - P_L", 1. - rgs_test.logical_qubit.P_succ)
 
        print(rgs_test.logical_qubit.R)
        print()

0.2000000000000000111
e_sp:  2.8e-05
miu 0.2000000000000000111
1 - PZ:  1.9650996989639679668e-06
1 - PX:  6.665029859916245247e-05
ez:  1.7327372111009664361e-07
ex:  2.6894857204974516e-06
1 - P_L 0.43532779728794341825
[0.99993335 0.99999939 0.8       ]

0.2000000000000000111
e_sp:  2.8e-05
miu 0.2000000000000000111
1 - PZ:  2.8956393714141270834e-05
1 - PX:  0.00038582195172141695765
ez:  1.5768862870063268274e-06
ex:  9.324703924978673e-06
1 - P_L 0.36177916362674764392
[0.99961418 0.99998684 0.8       ]

0.27
e_sp:  5.6e-05
miu 0.27
1 - PZ:  4.6841120217022691463e-06
1 - PX:  9.969801066210407306e-05
ez:  5.054521395865178841e-07
ex:  1.4067753739886092e-05
1 - P_L 0.42685974030863645394
[0.9999003  0.99999898 0.9271    ]

0.27
e_sp:  5.6e-05
miu 0.27
1 - PZ:  3.883355877520866528e-05
1 - PX:  0.000586464184981994323
ez:  2.861107695065726551e-06
ex:  4.7799668241155486e-05
1 - P_L 0.36698594911268605975
[0.99941354 0.99998801 0.9271    ]

