In [13]:
import numpy as np
import matplotlib.pyplot as plt
from importlib import reload
import tgs, rgs
import delay_feedback_line_cal as line
reload(tgs) 
reload(rgs) 
reload(line)

<module 'delay_feedback_line_cal' from '/Users/gordonwongyl/Documents/ORF/Reproduce_result/delay_feedback_line_cal.py'>

In [14]:
#TGS_ancilla
GAMMA = np.array([2e9, 100e9, 170e6, 100e9]) * 2 * np.pi
T_SPIN_COHERENCE = [13e-3, 4e-6, 1., 1.]
L_neighbour = [1.7e3, 30.3e3, 1.8e3, 1.7e3]
BRANCH_PARAM = [np.array([4,16,5]), np.array([1,1,19]), np.array([4,18,5]), np.array([4,16,5])]
L_delay = [398, 80.4, 627.9, 380.7]

L = 1000e3
L_ATT = 20e3

for i in range(len(GAMMA)):
    M = L/L_neighbour[i] - 1
    miu = tgs.Miu(L, L_ATT, L_delay=L_delay[i], m=M, L_feedback=0)
    tree = tgs.Tree_ancilla(BRANCH_PARAM[i], miu=miu)
    time = tgs.Time(GAMMA[i], 500)
    error = tgs.Error(tree, time, t_spin_coherence=T_SPIN_COHERENCE[i])

    print("M:", M)
    # print("Miu: ", tree.miu_total(delay_apply=False))
    # print("Tree P_succ", tree.P_succ)
    # print("Tree_ T graph:", tree.T_tree(time))
    # print("e_incorrect:", error.e_incorrect)
    print("R_eff: ", tgs.effective_key_rate(tree, time, error, M, 3))
    print()


M: 587.2352941176471
R_eff:  1770.4923306414776344

M: 32.00330033003301
R_eff:  3.4591894499162946578e-17

M: 554.5555555555555
R_eff:  1131.487974453647731

M: 587.2352941176471
R_eff:  1875.0637413611631633



In [15]:
#TGS_feedback
GAMMA = np.array([2e9, 100e9, 170e6, 100e9]) * 2 * np.pi
T_SPIN_COHERENCE = [13e-3, 4e-6, 1., 1.]
L_neighbour = [1.1e3, 2.2e3, 27e3, 1.9e3]
BRANCH_PARAM = [np.array([4,16,5]), np.array([4,22,6]), np.array([1,1,18]), np.array([4,15,5])]
L_feedback = [540.3, 16.5, 93.6, 11.3]
L_delay = [1.2e3, 37.1, 378., 25.6]

L = 1000e3
L_ATT = 20e3

for i in range(4):
    M = L/L_neighbour[i] - 1
    miu = tgs.Miu(L, L_ATT, L_delay=L_delay[i], m=M, L_feedback=L_feedback[i])
    tree = tgs.Tree_feedback(BRANCH_PARAM[i], miu=miu)
    time = tgs.Time(GAMMA[i], 500)
    error = tgs.Error(tree, time, t_spin_coherence=T_SPIN_COHERENCE[i])

    # print("M:", M)
    # print("Miu: ", tree.miu_total(delay_apply=False))
    # print("Tree P_succ", tree.P_succ)
    # print("Tree_ T graph:", tree.T_tree(time))
    # print("e_incorrect: ", error.e_incorrect)
    print("R_eff: ", tgs.effective_key_rate(tree, time, error, M, 2))
    print()



R_eff:  844.9444503685697714

R_eff:  131161.25816454378807

R_eff:  5.6193622841919149187e-18

R_eff:  188582.40288520495352



In [16]:
#RGS_ancilla
GAMMA = np.array([2e9, 100e9, 170e6, 100e9]) * 2 * np.pi
T_SPIN_COHERENCE = [13e-3, 4e-6, 1., 1.]
L_neighbour = [3.2e3, 500e3, 3.1e3, 3.2e3]
N = [32, 4, 32, 32]
BRANCH_PARAM = [np.array([24,7]), np.array([1,1]), np.array([24,7]), np.array([24,7])]
L_delay = [483.5, 20., 516.6, 480.5]

L = 1000e3
L_ATT = 20e3

for i in range(4):
    M = round(L/L_neighbour[i] - 1)
    miu = tgs.Miu(L/2, L_ATT, L_delay=L_delay[i], m=M, L_feedback=0)
    rgs_ancilla = rgs.RGS_ancilla(BRANCH_PARAM[i], N[i], miu=miu)
    time = tgs.Time(GAMMA[i], 500)
    error = rgs.RGS_Error(rgs_ancilla, time, T_SPIN_COHERENCE[i])
    # R_eff = rgs.effective_key_rate(rgs_ancilla, time, error, M, 3, L, L_ATT)

    print("M:", M)
    # print("Miu: ", rgs_ancilla.miu_total)
    # print("RGS P_succ", rgs_ancilla.P_succ)
    # print("RGS T graph:", rgs_ancilla.T_graph(time))
    print("R_eff: ", rgs.effective_key_rate(rgs_ancilla, time, error, M, 3, L, L_ATT))
    print()
    
    

M: 312
R_eff:  253.9797771340681499

M: 1
R_eff:  -9.393088618721498197e-49

M: 322
R_eff:  215.18688494737545606

M: 312
R_eff:  260.52244736028270322



In [17]:
#RGS_feedback
GAMMA = np.array([2e9, 100e9, 170e6, 100e9]) * 2 * np.pi
T_SPIN_COHERENCE = [13e-3, 4e-6, 1., 1.]
L_neighbour = [2.2e3, 3.9e3, 9.3e3, 3.8e3]
N = [14, 32, 4, 32]
BRANCH_PARAM = [np.array([13,5]), np.array([25, 7]), np.array([4, 2]), np.array([24, 7])]
L = 1000e3
L_ATT = 20e3

for i in range(4):
    M = round(L/L_neighbour[i] - 1)
    time = tgs.Time(GAMMA[i], 500)
    
    miu = tgs.Miu(L/2, L_ATT, L_delay=line.delay_line_rgs_feedback(BRANCH_PARAM[i], N[i],time), 
                  m=M, L_feedback=line.delay_line_rgs_feedback(BRANCH_PARAM[i], N[i],time))
    
    rgs_feedback = rgs.RGS_feedback(BRANCH_PARAM[i], N[i], miu=miu)
    error = rgs.RGS_Error(rgs_feedback, time, T_SPIN_COHERENCE[i])
    # R_eff = rgs.effective_key_rate(rgs_ancilla, time, error, M, 3, L, L_ATT)

    print("M:", M)
    # print("Miu: ", rgs_ancilla.miu_total)
    # print("RGS P_succ", rgs_ancilla.P_succ)
    # print("RGS T graph:", rgs_ancilla.T_graph(time))
    print("R_eff: ", rgs.effective_key_rate(rgs_feedback, time, error, M, 1, L, L_ATT))
    print()
    

M: 454
R_eff:  -4.4169851776213139009e-10

M: 255
R_eff:  20540.264947329818163

M: 107
R_eff:  6.4551390662880385054e-79

M: 262
R_eff:  40781.619682172011007



In [18]:
eta = 0.95
L_0 = 4e3 #
tau_a = 150e-9
m = 24 #
l_att = 22e3
b_i = np.array([16, 14, 1]) #
c = 2e8

tau_s = (np.log2(2*m) + np.sum([np.log2(b) for b in b_i]) + 2 + 4)*tau_a
tau_c = tau_a + tau_s
P = np.exp(-c*tau_a/l_att)
A = np.exp(-L_0/2/l_att)
B = P**((tau_c + 2*tau_a)/tau_a)
C = eta/(2-eta)

miu1 = 1 - A*B*C
miu1

m = 19
b_i = np.array([11, 11, 1])

tau_s = (np.log2(2*m) + np.sum([np.log2(b) for b in b_i]) + 2 + 4)*tau_a
tau_c = tau_a + tau_s
P = np.exp(-c*tau_a/l_att)
A = np.exp(-L_0/2/l_att)
B = P**((tau_c + 2*tau_a)/tau_a)
C = eta/(2-eta)

miu2 = 1 - A*B*C
miu2

L_0 = 8e3
m = 27
b_i = np.array([17, 28, 2])

tau_s = (np.log2(2*m) + np.sum([np.log2(b) for b in b_i]) + 2 + 4)*tau_a
tau_c = tau_a + tau_s
P = np.exp(-c*tau_a/l_att)
A = np.exp(-L_0/2/l_att)
B = P**((tau_c + 2*tau_a)/tau_a)
C = eta/(2-eta)

miu3 = 1 - A*B*C

m = 21
b_i = np.array([12, 23, 2])

tau_s = (np.log2(2*m) + np.sum([np.log2(b) for b in b_i]) + 2 + 4)*tau_a
tau_c = tau_a + tau_s
P = np.exp(-c*tau_a/l_att)
A = np.exp(-L_0/2/l_att)
B = P**((tau_c + 2*tau_a)/tau_a)
C = eta/(2-eta)

miu4 = 1 - A*B*C

In [19]:
# Check with data in A3
miu_set = [miu1, miu2, miu3, miu4]
e_m_set = [2.8e-5, 2.8e-5, 5.6e-5,  5.6e-5]
m = [24, 19, 27, 21]
n = [1249, 249, 624, 124]
e_Z = [1.55e-7, 1.35e-6, 5.15e-7, 2.75e-6]
e_X = [2.45e-6, 8.25e-6, 1.45e-5, 4.65e-5]

BRANCH_PARAM = [np.array([16,14,1], dtype=int), np.array([11, 11, 1]), 
                np.array([17,28,2]), np.array([12,23,2])]

for i in range(4):
        
        miu = tgs.Miu(1000, 100, 0, 0, 0, miu_set=miu_set[i])
        time = tgs.Time(2e9, 500) # shouldn't matter
        rgs_test = rgs.RGS_ancilla(BRANCH_PARAM[i], 2*m[i], miu=miu)
        # print(rgs_test.N)

        error = rgs.RGS_Error(rgs_test, time, 0, epsilon_sp_measure_set=e_m_set[i])
        print(error.e_I_k)

        print("1 - PZ: ", np.float128(1.0) - rgs_test.prob_Z_measurement)
        print("1 - PX: ", np.float128(1.0) - rgs_test.prob_X_measurement)

        print("ez: ", error.epsilon_Z)
        print("ex: ", error.epsilon_X)

        print("1 - P_L", 1. - rgs_test.logical_qubit.P_succ)

        print("P_succ: ", rgs_test.P_succ2(n[i]))
        print("F: ", rgs.RGS_fidelity(e_m=e_m_set[i], e_X= e_X[i], e_Z=e_Z[i], num_core_nodes=rgs_test.N, num_repeater_nodes=n[i]))
 
        # # print(rgs_test.logical_qubit.R)
        print()

[2.45838000e-06 1.01514243e-08 2.80000000e-05]
1 - PZ:  1.8008301947425309208e-06
1 - PX:  5.9026787237093873012e-05
ez:  1.6262602616250241611e-07
ex:  2.4583799955956137e-06
1 - P_L 0.43106473346112981538
P_succ:  0.69345746623623997373
F:  0.8890933362697888

[8.27262572e-06 1.30130598e-07 2.80000000e-05]
1 - PZ:  2.5097874717494583763e-05
1 - PX:  0.00032288956698395721197
ez:  1.4342793252548771325e-06
ex:  8.27262571785891e-06
1 - P_L 0.3540803775947291402
P_succ:  0.5823292727927261556
F:  0.9637295576040198

[1.46358849e-05 3.07591862e-08 5.60000000e-05]
1 - PZ:  4.900170429755767998e-06
1 - PX:  0.000105287556645699393286
ez:  5.2364522104421264925e-07
ex:  1.463588494009833e-05
1 - P_L 0.42896146453348941687
P_succ:  0.6452577155343866493
F:  0.8724617524513405

[4.66299861e-05 2.31720956e-07 5.60000000e-05]
1 - PZ:  3.7474446796914584468e-05
1 - PX:  0.0005649461849701878022
ez:  2.7863108981183152967e-06
ex:  4.662998614301667e-05
1 - P_L 0.36517770519802595437
P_succ:  0.6