In [1]:
import numpy as np
import matplotlib.pyplot as plt
from importlib import reload
import tgs, rgs
reload(tgs) 
reload(rgs) 


<module 'rgs' from '/Users/gordonwongyl/Documents/ORF/Reproduce_result/rgs.py'>

In [2]:
GAMMA = np.array([2e9, 100e9, 170e6, 100e9]) * 2 * np.pi
T_SPIN_COHERENCE = [13e-3, 4e-6, 1., 1.]
L_neighbour = [1.7e3, 30.3e3, 1.8e3, 1.7e3]
BRANCH_PARAM = [np.array([4,16,5]), np.array([1,1,19]), np.array([4,18,5]), np.array([4,16,5])]
L_delay = [398, 80.4, 627.9, 380.7]

L = 1000e3
L_ATT = 20e3

for i in range(len(GAMMA)):
    M = L/L_neighbour[i] - 1
    miu = tgs.Miu(L, L_ATT, L_delay=L_delay[i], m=M)
    tree = tgs.Tree_ancilla(BRANCH_PARAM[i], miu=miu)
    time = tgs.Time(GAMMA[i], 500)
    error = tgs.Error(tree, time, t_spin_coherence=T_SPIN_COHERENCE[i])

    print(tree.R)
    print("M:", M)
    # print("Miu: ", tree.miu_total(delay_apply=False))
    # print("Tree P_succ", tree.P_succ)
    # print("Tree_ T graph:", tree.T_tree(time))
    # print("e_incorrect:", error.e_incorrect)
    print("R_eff: ", tgs.effective_key_rate(tree, time, error, M, 2))
    print()


[0.99973596 0.99991018 0.99996642]
M: 587.2352941176471
R_eff:  2640.0859973303215202

[2.06888928e-01 2.48689958e-14 9.88325080e-01]
M: 32.00330033003301
R_eff:  3.8797236227187776568e-17

[0.99969781 0.99995754 0.99996028]
M: 554.5555555555555
R_eff:  854.76710112484905213

[0.99973596 0.99991018 0.99996642]
M: 587.2352941176471
R_eff:  3344.0385096199860184



In [5]:
GAMMA = np.array([2e9, 100e9, 170e6, 100e9]) * 2 * np.pi
T_SPIN_COHERENCE = [13e-3, 4e-6, 1., 1.]
L_neighbour = [1.1e3, 2.2e3, 27e3, 1.9e3]
BRANCH_PARAM = [np.array([4,16,5]), np.array([4,22,6]), np.array([1,1,18]), np.array([4,15,5])]
L_feedback = [540.3, 16.5, 93.6, 11.3]
L_delay = [1.2e3, 37.1, 378., 25.6]

L = 1000e3
L_ATT = 20e3

for i in range(4):
    M = L/L_neighbour[i] - 1
    miu = tgs.Miu(L, L_ATT, L_delay=L_delay[i], m=M, L_feedback=L_feedback[i])
    tree = tgs.Tree_feedback(BRANCH_PARAM[i], miu=miu)
    time = tgs.Time(GAMMA[i], 500)
    error = tgs.Error(tree, time, t_spin_coherence=T_SPIN_COHERENCE[i])

    # print("M:", M)
    # print("Miu: ", tree.miu_total(delay_apply=False))
    # print("Tree P_succ", tree.P_succ)
    # print("Tree_ T graph:", tree.T_tree(time))
    # print("e_incorrect: ", error.e_incorrect)
    print("R_eff: ", tgs.effective_key_rate(tree, time, error, M, 1))
    print()



R_eff:  5348.3814366165690304

R_eff:  270432.33447677267515

R_eff:  1.36974726696793735885e-17

R_eff:  386891.79985093300604



In [4]:
GAMMA = np.array([2e9, 100e9, 170e6, 100e9]) * 2 * np.pi
T_SPIN_COHERENCE = [13e-3, 4e-6, 1., 1.]
L_neighbour = [3.2e3, 500e3, 3.1e3, 3.2e3]
N = [32, 4, 32, 32]
BRANCH_PARAM = [np.array([24,7]), np.array([1,1]), np.array([24,7]), np.array([24,7])]
L_delay = [483.5, 20., 516.6, 480.5]

L = 1000e3
L_ATT = 20e3

for i in range(4):
    M = round(L/L_neighbour[i] - 1)
    miu = tgs.Miu(L/2, L_ATT, L_delay=L_delay[i], m=M)
    rgs_ancilla = rgs.RGS_ancilla(BRANCH_PARAM[i], N[i], miu=miu)
    time = tgs.Time(GAMMA[i], 500)
    error = rgs.RGS_Error(rgs_ancilla, time, T_SPIN_COHERENCE[i])
    # R_eff = rgs.effective_key_rate(rgs_ancilla, time, error, M, 3, L, L_ATT)

    print("M:", M)
    # print("Miu: ", rgs_ancilla.miu_total)
    # print("RGS P_succ", rgs_ancilla.P_succ)
    # print("RGS T graph:", rgs_ancilla.T_graph(time))
    print("R_eff: ", rgs.effective_key_rate(rgs_ancilla, time, error, M, 3, L, L_ATT))
    print()
    
    

M: 312
R_eff:  332.30858820905231252

M: 1
R_eff:  -7.4427089430450249104e-81

M: 322
R_eff:  282.16252584492061842

M: 312
R_eff:  339.2968840142396355



In [7]:
# Check with data in A3
miu_set = [np.float128(0.1987), 0.27]
e_m_set = [2.8e-5, 5.6e-5]
BRANCH_PARAM = [[np.array([16,14,1], dtype=int), np.array([11, 11, 1])], 
                [np.array([17,28,2]), np.array([12,23,2])]]

for i in range(2):
    for j in range(2):
        miu = tgs.Miu(1000, 100, 0, 0, 0, miu_set=miu_set[i])
        time = tgs.Time(2e9, 500) # shouldn't matter
        rgs_test = rgs.RGS_ancilla(BRANCH_PARAM[i][j], 0, miu=miu)

        error = rgs.RGS_Error(rgs_test, time, 0, epsilon_sp_measure_set=e_m_set[i])
        print("1 - PZ: ", np.float128(1.0) - rgs_test.prob_Z_measurement)
        print("1 - PX: ", np.float128(1.0) - rgs_test.prob_X_measurement)

        print("ez: ", error.epsilon_Z)
        print("ex: ", error.epsilon_X)

        print("1 - P_L", 1. - rgs_test.logical_qubit.P_succ)
 
        # print(rgs_test.logical_qubit.R)
        print()

1 - PZ:  1.8000820832808628325e-06
1 - PX:  5.8992612506050606195e-05
ez:  1.6257692129340754642e-07
ex:  2.4573257083845456e-06
1 - P_L 0.4310445115695992467

1 - PZ:  2.6990336650989377176e-05
1 - PX:  0.00035351610747623392122
ez:  1.5051211706287513824e-06
ex:  8.793086483465904e-06
1 - P_L 0.3579772780033453162

1 - PZ:  4.6841120217022691463e-06
1 - PX:  9.969801066210407306e-05
ez:  5.054521395865178841e-07
ex:  1.4067753739886092e-05
1 - P_L 0.42685974030863645394

1 - PZ:  3.883355877520866528e-05
1 - PX:  0.000586464184981994323
ez:  2.861107695065726551e-06
ex:  4.7799668241155486e-05
1 - P_L 0.36698594911268605975

